apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-node
  template:
    metadata:
      labels:
        app: api-node
    spec:
      containers:
      - name: api-node
        image: <<preenchido automaticamente>>
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "150m"
        env:
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: api-node-configmap
              key: API_PORT
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-node-service
spec:
  type: LoadBalancer
  selector:
    app: api-node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-node-configmap
data:
  API_PORT: "3000"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-node-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-node
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70