{
 "title": "api-node",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{container=~\"api-node.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(pod) (container_memory_usage_bytes{pod=~\"$pod\"}) * 100) / sum by(pod) (kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(pod) (container_memory_usage_bytes{pod=~\"$pod\"}) * 100) / sum by(pod) (kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[5m])) * 100) / sum by(pod) (kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[5m])) * 100) / sum by(pod) (kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"api-node.*\"})",
     "legendFormat": "Number of replicas"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"api-node.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{container=\"api-node\", pod=~\"$pod\"} |= ``"
    }
   ]
  }
 ]
}