name: api-node
on:
  push:
    branches: [ "test_deploy" ]
jobs:
  api-node-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v4

    - name: Cofiguring Git
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email ${GITHUB_ACTOR}@github.com

    - name: Get the source branch name
      run: |
        SOURCE_BRANCH=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls?state=closed | jq -r ".[] | select(.merge_commit_sha==\"${{ github.sha }}\") | .head.ref")
        echo "SOURCE_BRANCH=$SOURCE_BRANCH" >> $GITHUB_ENV
        
        echo "Deploy iniciado a partir de merge da branch $SOURCE_BRANCH"

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get release type
      run: |
        if [[ "$SOURCE_BRANCH" == release/* ]]; then
          RELEASE_TYPE=major
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
        elif [[ "$SOURCE_BRANCH" == feature/* ]]; then
          RELEASE_TYPE=minor
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
        elif [[ "$SOURCE_BRANCH" == hotfix/* ]]; then
          RELEASE_TYPE=patch
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
        else
          RELEASE_TYPE=patch
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
        fi

        echo "Tipo de release: $RELEASE_TYPE"

    - name: Bump version
      run: |
        VERSION=$(npm version $RELEASE_TYPE -m "$RELEASE_TYPE version %s"| cut -c2-)
        git push origin ${{ github.ref }}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Nova versão: $VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    - name: Docker Build
      run: docker build -t api-node-upbet:$VERSION .

    - name: Docker Push
      run: |
        echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        docker tag api-node-upbet:$VERSION ${{ secrets.DOCKER_USER }}/api-node-upbet:$VERSION
        docker push ${{ secrets.DOCKER_USER }}/api-node-upbet:$VERSION

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        target_commitish: ${{ env.BRANCH_NAME }}
        name: v${{ env.VERSION }}
        body: |
          Release gerada a partir da branch ${{ env.SOURCE_BRANCH }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v4
    
    - name: Set up deployment file
      run: "find ./deploy -name '*.yml' -exec sed -i 's/image: .*/image: ${{ secrets.DOCKER_USER }}api-node-upbet:${{ env.VERSION }}/' {} +"

    - name: Deploy
      run: kubectl apply -f ./deploy/ --server=${{ secrets.KUBERNETES_URL }} --token=${{ secrets.KUBERNETES_TOKEN }} --insecure-skip-tls-verify