name: api-node
on:
  push:
    branches: [ "pipeline" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cofiguring Git
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email gh-actions-${GITHUB_ACTOR}@github.com

    - name: Get release type
      run: |
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
        if [[ "$BRANCH_NAME" == release/* ]]; then
          RELEASE_TYPE=major
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
        elif [[ "$BRANCH_NAME" == feature/* ]]; then
          RELEASE_TYPE=minor
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
        elif [[ "$BRANCH_NAME" == hotfix/* ]]; then
          RELEASE_TYPE=patch
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
        else
          RELEASE_TYPE=patch
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
        fi

        echo "Tipo de release: $RELEASE_TYPE"

    - name: Bump version
      run: |
        VERSION=$(npm version $RELEASE_TYPE | cut -c2-)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Nova versão: $VERSION"

    - name: Docker Build
      run: docker build -t node-hello-api:$VERSION .
